<?php
/**
 * Summary: This was copied from the core Omeka S view directory view/common/advanced-search
 * from commit 534ed98b4970b23b8841b5b80cf9375317c6d92d.
 *
 * Purpose: This instance uses a local view helper allUserSelect to generate the form element
 * because the core view helper userSelect can not accept query parameter, and we need to pass
 * passes the 'bypass_team_filter' => true to the query used to populate
 * the user select element. This allows users with the 'bypass_team_filter' permission
 * to see all the installations users, not just those that are members of the current team.
 * This facilitates populating new teams with existing users.
 *
 * Notes: This file should be patched when upgrading the core software so that the advanced search
 * elements continue to reflect the changes in the core software. Create a patch using git diff
 * using the commit hash listed below and applying the patch to this file . Then update the commit
 * listed under Most recent patch.
 *
 * Most recent patch: 534ed98b4970b23b8841b5b80cf9375317c6d92d
 *
 */
?>

<div class="field">
    <div class="field-meta">
        <label for="owner_id"><?php echo $this->translate('Search by owner'); ?></label>
        <?php echo $this->hyperlink('', '#', ['class' => 'expand', 'title' => $this->translate('Expand')]); ?>
        <div class="collapsible">
            <div class="field-description"><?php echo $this->translate('Searches for resources that are owned by this user.'); ?></div>
        </div>
    </div>
    <div class="inputs">
        <?php echo $this->allUserSelect([
            'name' => 'owner_id',
            'attributes' => [
                'id' => 'owner_id',
                'value' => $query['owner_id'] ?? null,
            ],
            'options' => [
                'query' => ['bypass_team_filter' => true]
            ]

        ]); ?>
    </div>
</div>
