<?php
/**
 * Summary: This was copied from the core Omeka S view directory view/common/advanced-search
 * from commit 534ed98b4970b23b8841b5b80cf9375317c6d92d.
 *
 * Purpose: This instance passes the 'bypass_team_filter' => true to the query used to populate
 * the resource-template select element. This allows users with the 'bypass_team_filter' permission
 * to see all the installations resource-templates, not just those that belong to the current team.
 * This facilitates populating new teams with existing resource-templates.
 *
 * Notes: This file should be patched when upgrading the core software so that the advanced search
 * elements continue to reflect the changes in the core software. Create a patch using git diff
 * using the commit hash listed below and applying the patch to this file . Then update the commit
 * listed under Most recent patch.
 *
 * Most recent patch: 534ed98b4970b23b8841b5b80cf9375317c6d92d
 *
 */

$translate = $this->plugin('translate');

// Prepare the resource template query.
$ids = isset($query['resource_template_id']) ? $query['resource_template_id'] : [];
if (!is_array($ids)) {
    $ids = [$ids];
}
$ids = array_filter($ids);
if (!$ids) {
    $ids = [null];
}
?>
<div id="resource-templates" class="field removable multi-value" role="group">
    <div class="field-meta">
        <span id="by-resource-template-label" class="label"><?php echo $translate('Search by template'); ?></span>
        <?php echo $this->hyperlink('', '#', ['class' => 'expand', 'title' => $translate('Expand')]); ?>
        <div class="collapsible">
            <div class="field-description"><?php echo $translate('Searches for resources that use any of these templates.'); ?></div>
        </div>
        <button type="button" class="add-value o-icon-add button" aria-label="<?php echo $translate('Add new template'); ?>" title="<?php echo $translate('Add new template'); ?>"></button>
    </div>
    <div class="inputs">
        <?php foreach ($ids as $id): ?>
            <div class="value">
                <?php echo $this->resourceTemplateSelect([
                    'name' => 'resource_template_id[]',
                    'attributes' => [
                        'value' => $id,
                        'aria-labelledby' =>  'by-resource-template-label'
                    ],
                    'options' => [
                        'query' => ['bypass_team_filter' => true]
                    ]
                ]); ?>
                <button type="button" class="o-icon-delete remove-value button" aria-label="<?php echo $translate('Remove value'); ?>" title="<?php echo $translate('Remove value'); ?>"></button>
            </div>
        <?php endforeach; ?>
    </div>
</div>
