<?php $this->htmlElement('body')->appendAttribute('class', 'add resource-templates'); ?>

<?php echo $this->pageTitle($this->translate('New resource template'), 1, $this->translate('Resource templates')); ?>

<?php
echo $this->partial(
    'teams/resource-template/form.phtml',
    [
        'form' => $form,
        'propertyRows' => $propertyRows,
        'submitLabel' => $this->translate('Add'),
        'action' => 'add',
        'user_teams' => $this->user_teams,
        'rt_teams' => $this->rt_teams,
    ]
);
?>

<?php $this->trigger('view.add.after'); ?>
