<?php $this->htmlElement('body')->appendAttribute('class', 'edit resource-templates'); ?>

<?php echo $this->pageTitle($resourceTemplate->label(), 1, $this->translate('Resource templates')); ?>

<?php


echo $this->partial(
    'teams/resource-template/form.phtml',
    [
        'form' => $form,
        'resourceTemplate' => $resourceTemplate,
        'propertyRows' => $propertyRows,
        'submitLabel' => $this->translate('Save'),
        'action' => 'edit',
        'user_teams' => $this->user_teams,
        'rt_teams' => $this->rt_teams,
    ]
);
?>

<?php $this->trigger('view.edit.after'); ?>
