<?php $this->htmlElement('body')->appendAttribute('class', 'edit resource-templates'); ?>

<?php echo $this->pageTitle($resourceTemplate->label(), 1, $this->translate('Resource templates')); ?>

<?php
echo 'is it there:' . in_array(5, array_keys($this->rt_teams)) . '<br>';
foreach ( array_keys($this->rt_teams) as $keys):
echo $keys;
endforeach;
if ($this->data){
    foreach (array_keys($this->data) as $key):
        echo $key;
        echo '<br>';
    endforeach;
}
//echo $this->sectionNav([
//    'orig' => $this->translate('Before'),
//    'teams' => $this->translate('Teams')
//]);
echo count($this->rt_teams);

echo $this->partial(
    'teams/resource-template/form.phtml',
    [
        'form' => $form,
        'resourceTemplate' => $resourceTemplate,
        'propertyRows' => $propertyRows,
        'submitLabel' => $this->translate('Save'),
        'action' => 'edit',
        'user_teams' => $this->user_teams,
        'rt_teams' => $this->rt_teams,
    ]
);
?>

<?php $this->trigger('view.edit.after'); ?>
