<?php
$form->prepare();
$escape = $this->plugin('escapeHtml');
$this->headScript()->appendFile($this->assetUrl('vendor/sortablejs/Sortable.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/resource-template-form.js', 'Omeka'));
?>



<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <?php if (isset($resourceTemplate)): ?>
    <a href="#" class="delete button sidebar-content" data-sidebar-selector="#delete"><?php echo $this->translate('Delete'); ?></a>
    <?php endif; ?>
    <?php echo $this->cancelButton(); ?>
    <button><?php echo $escape($submitLabel); ?></button>
</div>
<div>
<?php $this->trigger("view.$action.form.before", ['form' => $form]); ?>

<?php echo $this->formCollection($form, false); ?>
<div class="field">
    <div class="field-meta">
        <label for="team">Team</label>
    </div>

    <div class="inputs">
        <select name="team[]" class="chosen-select" data-placeholder="Add to team" multiple="multiple">
            <? foreach ($this->user_teams as $id => $team):?>

                <option value="<? echo $id;?>" <?if (in_array($id, array_keys($this->rt_teams))){?>selected<?}?>><? echo $team?></option>
            <?endforeach;?>
            <?
            foreach (array_diff(array_keys($this->rt_teams), array_keys($this->user_teams)) as $id):?>
                                <option value="<? echo $id ?>" selected disabled><? echo $this->rt_teams[$id] ?></option>
            <?
            endforeach;

            ?>
<!--                <option value="3" disabled>Option 3</option>-->
        </select>

    </div>


</div>

<ul id="properties" data-add-new-property-row-url="<?php echo $escape($this->url(null, ['action' => 'add-new-property-row'], true)); ?>">

    <?php foreach ($propertyRows as $propertyRow): ?>
    <?php echo $this->partial(
        'teams/resource-template/show-property-row',
        ['propertyRow' => $propertyRow]
    ) ?>
    <?php endforeach; ?>

</ul>
<?php $this->trigger("view.$action.form.after", ['form' => $form]); ?>

<button id="property-selector-button" class="mobile-only"><?php echo $this->translate('Add property'); ?></button>


<?php echo $this->propertySelector(); ?>
<?php if (isset($resourceTemplate)): ?>
    <?php echo $this->deleteConfirm($resourceTemplate, 'resource template'); ?>
<?php endif; ?>
</div>
<div >
<div id="properties" form="resourcetemplateform">
<!--    --><?//echo $this->partial('teams/partial/team-form-no-id')?>
        <legend id="teams-legend"><?php echo $this->translate('Teams'); ?></legend>
        <table id="team-resources" data-tablesaw-mode="stack" class="tablesaw tablesaw-stack <?php echo ( $teams) ? '' : 'empty'; ?>">
            <thead>
            <tr>
                <th><?php echo $this->translate('Team Name'); ?></th>
                <th style="float: right"><?php echo $this->translate('Remove'); ?> </th>
            </tr>
            </thead>
            <?php foreach ($this->rt_teams as $id=>$team): ?>
                <tr>
                    <td>
                        <span><?php echo $team?></span>

                        <input type="hidden" name="teamtest" value="<?php echo $id ?>">
                    </td>
                    <td>
                        <ul class="actions" style="float:right">
                            <li>

                                <a href="#" class="o-icon-delete" title="<?php echo $removeStr; ?>" aria-label="<?php echo $removeStr; ?>"></a>
                            </li>
                        </ul>
                    </td>
                </tr>
                <tr>

                </tr>


            <?php endforeach; ?>

        </table>

</div>
</div>
<?php echo $this->form()->closeTag(); ?>

<div id="details" class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $this->translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>

<div id="edit-sidebar" class="sidebar">
    <div class="confirm-main">
        <?php echo $this->hyperlink('', '#', [
            'class' => 'sidebar-close o-icon-close',
            'title' => $this->translate('Close'),
        ]); ?>
        <div class="field">
            <h3><?php echo $escape($this->translate('Label')); ?></h3>
            <h4><?php echo $this->translate('Original'); ?></h4>
            <span id="original-label"></span>
            <label for="alternate-label"><?php echo $this->translate('Alternate'); ?></label>
            <input id="alternate-label" type="text">
        </div>
        <div class="field">
            <h3><?php echo $escape($this->translate('Comment')); ?></h3>
            <h4><?php echo $this->translate('Original'); ?></h4>
            <span id="original-comment"></span>
            <label for="alternate-comment"><?php echo $this->translate('Alternate'); ?></label>
            <textarea id="alternate-comment"></textarea>
        </div>
        <div class="field">
            <h3><?php echo $this->translate('Other options'); ?></h3>
            <div class="option">
                <label for="is-required">
                    <?php echo $this->translate('Required'); ?>
                    <input id="is-required" type="checkbox">
                </label>
            </div>
            <div class="option">
                <label for="is-private">
                    <?php echo $this->translate('Private'); ?>
                    <input id="is-private" type="checkbox">
                </label>
            </div>
            <div class="option">
                <label for="data-type"><?php echo $this->translate('Data type'); ?></label>
                <?php echo $this->dataType()->getSelect('data_type', null, ['id' => 'data-type', 'class' => 'chosen-select']); ?>
            </div>
        </div>
    </div>
    <div class="confirm-panel">
        <button id="set-changes"><?php echo $this->translate('Set changes'); ?></button>
    </div>
</div>
