<?php
$escape = $this->plugin('escapeHtml');
?>
<div id="resource-class-selector" class='selector sidebar <?php echo $state; ?>'>
    <?php if ($text) :?>
    <p><?php echo $escape($text); ?></p>
    <?php else: ?>
    <p><?php echo $this->translate('Click on a resource class to add it to the mapped item types.'); ?></p>
    <?php endif; ?>
    <input type="text" class="selector-filter" placeholder="<?php echo $this->translate('Filter resource classes'); ?>">
    <ul>
        <li class="show"><?php echo $this->translate('All resource classes'); ?>
            <ul>
                <?php foreach ($vocabularies as $vocabulary): ?>
                <?php
                $classes = $vocabulary->resourceClasses();
                if (!$classes) {
                    // Do not render vocabularies without class. They suck.
                    continue;
                }
                ?>
                <li class='selector-parent'
                    data-vocabulary-id="<?php echo $escape($vocabulary->id()); ?>">
                    <span><?php echo $escape($vocabulary->label()); ?></span> (<span class="selector-child-count"><?php echo count($vocabulary->resourceClasses()); ?></span>)
                    <ul>
                        <?php foreach ($classes as $class): ?>
                        <li class='selector-child'
                            data-child-search="<?php echo $escape($class->label()); ?>"
                            data-class-id="<?php echo $escape($class->id()); ?>"
                            data-class-term="<?php echo $escape($class->term()); ?>">
                            <div class="description">
                                <p class="o-icon-info"><span class="screen-reader-text"><?php echo $this->translate('More info'); ?></span></p>
                                <p class="field-comment"><?php echo $escape($class->comment()); ?></p>
                            </div>
                            <span><?php echo $escape($class->label()); ?></span>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </li>
                <?php endforeach; ?>
            </ul>
        </li>
    </ul>
</div>
