<div id='users-sidebar' class='sidebar always-open flags'>
    <h3><?php echo $this->translate("Users info"); ?></h3>
    <ul>
        <li data-flag='column-user-email'>
            <a href='#' class='button'><span><?php echo $this->translate("Email"); ?></span></a>
        </li>
        <li data-flag='column-user-displayname'>
            <a href='#' class='button'><span><?php echo $this->translate("Display name"); ?></span></a>
        </li>
        <li data-flag='column-user-role'>
            <a href='#' class='button'><span><?php echo $this->translate("Role"); ?></span></a>
        </li>
    </ul>
</div>
