<script>
    window.addEventListener("load", function () {
        $(".remove-user").click(function(){
            $(this).closest("tr").toggleClass('delete');
            if ($(this).closest("tr").hasClass('delete')){
                $(this).closest("tr").find("select").attr('disabled', true)
            } else {$(this).closest("tr").find("select").removeAttr('disabled')}
            $(this).toggleClass('o-icon-delete');
            $(this).toggleClass('fa');
            $(this).toggleClass('fa-undo');
        });
    })
</script>
<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'items edit');

$sectionNavs = [
    'team-info' => $translate('Info'),
    'team-members' => $translate('Users'),
    'team-resources' => $translate('Resources'),
    'team-sites' => $translate('Sites'),
//    'team-assets' => $translate('Assets')
];
?>
<?php echo $this->sectionNav($sectionNavs, 'view.show.section_nav'); ?>

<h1>Update Team for <?php echo $this->form->get('o:name')->getValue()?></h1>
<div id="page-actions">
        <?php echo $this->cancelButton(); ?>
    <button type="submit" form="team-update-form" value="Submit">Save Edits</button>
</div>
<?php
$form = $this->form;

$form->prepare();

echo $this->form()->openTag($form);?>

<div id="team-info" class="active section">
    <div class="meta-group">
        <?php echo $this->formCollection($form); ?>
    </div>
</div>
<?php echo $this->form()->openTag($form);?>

<?php if ($this->roleAuth()->teamAuthorized('update', 'team_user')): ?>

    <fieldset id="team-members" class="section">
    <!--    --><?php //$userRoleForm = $this->userRoleForm;
//    $userRoleForm->prepare();
//    echo $this->form()->openTag($userRoleForm);
//    echo $this->formCollection($userRoleForm);
//    ?>
    <?php echo $this->partial('teams/team/manage-users', [
        'users' => $this->users,
        'team' => $this->team,

    ]);
    ?>
    </fieldset><?php endif; ?>

<?php if ($this->roleAuth()->teamAuthorized('update', 'team')): ?>
<div id="team-resources" class="section">
    <div class="selection-criteria">
        <div class="select-by-item-set-content">
            <?php
            $itemsetForm = $this->itemsetForm;
            $fs = $itemsetForm->getFieldsets();
            $fs['addCollections']->setLabel('Add resources to team');
            $fs['rmCollections']->setLabel('Remove resources from team');
            $itemsetForm->prepare();
            echo $this->form()->openTag($itemsetForm);
            echo $this->formCollection($itemsetForm);
            ?>
        </div>
    </div>
</div>
<?php else: ?>
    <div id="team-resources" class="section">
        <p>You are only authorized to Manage Team Users</p>
    </div>
<?php endif; ?>
<?php if ($this->roleAuth()->teamAuthorized('update', 'team')): ?>
    <div id="team-sites" class="section">
        <div class="selection-criteria">
            <div class="select-by-item-set-content">
                <?php
                $sitesForm = $this->sitesForm;
                $fs = $sitesForm->getFieldsets();
                $fs['teamSites']->setLabel('Add or Remove Sites ');
                $sitesForm->prepare();
                echo $this->form()->openTag($sitesForm);
                echo $this->formCollection($sitesForm);
                echo $this->form()->closeTag($sitesForm)
                ?>
            </div>
        </div>
    </div>
<?php else: ?>
    <div id="team-sites" class="section">
        <p>You are only authorized to Manage Team Users</p>
    </div>
<?php endif; ?>
<?php echo $this->form()->closeTag(); ?>

