<?php
$this->headScript()->appendFile($this->assetUrl('vendor/sortablejs/Sortable.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/site-resources.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/inject-removal-util-element.js', 'Teams'));
$this->headScript()->appendFile($this->assetUrl('js/team-users.js', 'Teams'));
$this->headLink()->prependStylesheet($this->assetUrl('css/teams.css', 'Teams'));

$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'teams edit');
?>
<?php echo $this->pageTitle($this->teamRepresentation->name(), 1, $translate('Teams'), $translate('Edit')); ?>
<?php $this->trigger('view.edit.before'); ?>

<?php echo $this->partial('teams/team/edit-form', [
    'form'                   => $this->form,
    'resourceForm'           => $this->resourceForm,
    'secondaryResourcesForm' => $this->secondaryResourcesForm,
    'sitesForm'              => $this->sitesForm,
    'team'                   => $this->team,
    'bypassTeamFilterRoles'  => $this->bypassTeamFilterRoles,
    'user'                   => $this->user,
    'isAdd'                  => false,
    'sectionNavEvent'        => 'view.edit.section_nav',
    'action'                 => 'edit',
]); ?>

<?php echo $this->deleteConfirm($this->teamRepresentation, 'team'); ?>

<?php $this->trigger('view.edit.after'); ?>
