<h1>Add New Team</h1>
<?php

$this->htmlElement('body')->appendAttribute('class', 'add users');

$this->headLink()->prependStylesheet($this->assetUrl('css/teams.css', 'Teams'));
$this->headLink()->prependStylesheet($this->assetUrl('css/teams.css', 'Teams'));

if ($this->response){
    echo count($response) . '<br>';
    foreach ($response as $item):
        echo $item->id();

    endforeach;

}
?>
<div id="page-actions">
    <!--    --><?php //if ($item->userIsAllowed('update')): ?>
    <button type="submit" form="new_team" value="Submit">Add Team</button>
    <!--    --><?php //endif; ?>
</div>
<?php

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

//$this->htmlElement('body')->appendAttribute('class', 'items edit');
$sectionNavs = [
    'team-info' => $translate('Info'),
    'team-members' => $translate('Users'),
    'team-resources' => $translate('Resources'),
];
echo $this->sectionNav($sectionNavs, 'view.add.section_nav');
?>

<div id="team-info" class="active section">
    <div class="meta-group">

<?php



$form = $this->form;
$form->setAttribute('id', 'new_team');
$form->setAttribute('action', $this->url());
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formCollection($form);

?>
    </div>
</div>

<div id="team-members" class="section">
    <div class="meta-group">
        <div class="field">
            <div class="field-meta">
                <label for="add-member-choice">Add a User and Assign them a Role:</label>
            </div>
            <div class="input">
                <input class="chzn-select"  placeholder="Username" list="add-member-options" id="new-member-choice" name="add-member-choice" />
            </div>
<!--            <script type="text/javascript">-->
<!--                $(function() {-->
<!--                    $(".chzn-select").chosen();-->
<!--                });-->
<!--            </script>-->
<!--            <div class="input">-->
<!--                <select class="chzn-select" multiple="false" name="faculty" style="width:200px;">-->
<!--                    <option value="AC">A</option>-->
<!--                    <option value="AD">B</option>-->
<!--                    <option value="AM">C</option>-->
<!--                    <option value="AP">D</option>-->
<!--                </select>-->
<!--            </div>-->



            <datalist id="add-member-options">
                <? foreach (array_keys($this->available_u_array) as $member):
                    echo '<option value="' .  $member .'" id="user' . $this->available_u_array[$member] . '"> ';
                endforeach;
                ?>
            </datalist>




            <div class="input">
                <input class="row-left" placeholder="Role" list="add-member-role" id="new-member-role" name="add-member-role" />
            </div>


            <datalist id="add-member-role">
                <? foreach (array_keys($this->roles) as $role):
                    echo '<option value="' .  $role .'"> ';
                endforeach;
                ?>
            </datalist>
            <script>
                function removeRow(id,u){
                    let row = document.getElementById(id);
                    row.parentElement.removeChild(row);
                    let user_options = document.getElementById("add-member-options");
                    let option = document.createElement('option');

                    option.setAttribute('value', u);
                    option.setAttribute('id', id);

                    user_options.appendChild(option);


                }

                users = <? echo json_encode($this->available_u_array);?>;
                roles = <? echo json_encode($this->roles);?>;
                function addUser() {
                    let nm = document.getElementById("new-member-choice");
                    let nmr = document.getElementById("new-member-role");

                    // alert("role" + roles[nmr.value]);


                    let row = document.createElement('tr');
                    row.id = "u" + users[nm.value];
                    let userNameTd = document.createElement('td');
                    let trashA = document.createElement('a');
                    trashA.setAttribute("class", "o-icon-delete");
                    trashA.classList.add("row-left")
                    trashA.setAttribute("onclick", "removeRow('" + row.id +"', '"+ nm.value + "')");
                    userNameTd.appendChild(trashA);
                    let userA = document.createElement('a');
                    userA.setAttribute('href', window.location.hostname + '/admin/user' + nm.value);
                    userA.innerText = nm.value;
                    userNameTd.appendChild(userA);
                    let selected = document.createElement('input');
                    selected.setAttribute('type', 'hidden');
                    selected.setAttribute('form','new_team');
                    selected.setAttribute('name', 'user_role[' + users[nm.value] +']');
                    selected.value = roles[nmr.value] ;

                    row.appendChild(selected);


                    row.appendChild(userNameTd);
                    document.getElementById("user-table").appendChild(row);

                    let roleTd = document.createElement('td');
                    roleTd.innerText = nmr.value ;

                    let user_option = document.getElementById('user' + users[nm.value]);
                    user_option.parentElement.removeChild(user_option);

                    row.appendChild(roleTd);
                    nmr.value = "";
                    nm.value = "";
                }
            </script>
            <div style="margin-left: 20px; ">
                <button type="button" class="o-icon-add" onclick="addUser()" href='javascript:void()'> add</button>
            </div>
        </div>
        <div class="field">
            <div class="field-meta">
                Current Users:
            </div>
                <table class="tablesaw batch-edit" data-tablesaw-mode="stack">
                    <thead>
                    <tr>
                        <th>
                            <?php echo $translate('Name'); ?>
                        </th>
                        <th><?php echo $translate('Role'); ?></th>
                        <th><?php echo $translate('Created'); ?></th>
                    </tr>
                    </thead>
                    <tbody id="user-table">

                    </tbody>
                </table>

        </div>

    </div>
</div>

<div id="team-resources" class="section">
    <p>TODO: this is not yet connected to logic that turns the advanced search into </p>



    <div class="selection-criteria">
        <p>
            All items belonging to these itemsets or owners will be added to the group
        </p>
        <div class="select-by-item-set-content">

            <?
            $itemsetForm = $this->itemsetForm;
            $itemsetForm->setAttribute('id', 'itemset_collection');
            $itemsetForm->setAttribute('action', $this->url());
            $itemsetForm->prepare();

            echo $this->form()->openTag($itemsetForm);

            echo $this->formCollection($itemsetForm);
            echo $this->form()->closeTag($itemsetForm)
            ?>

        </div>
    </div>

</div>


<?php
echo $this->form()->closeTag();
