<?php
echo $this->pageTitle("Add new team");
if ($this->roleAuth()->teamAuthorized('add', 'team')):

$this->htmlElement('body')->appendAttribute('class', 'add');
$this->headLink()->prependStylesheet($this->assetUrl('css/teams.css', 'Teams'));
$this->headScript()->appendFile($this->assetUrl('js/team-users.js', 'Teams'));
$formElement = $this->plugin('formElement');
?>
<div id="page-actions">
    <button type="submit" form="new_team" value="Submit">Add team</button>
</div>
<?php

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$sectionNavs = [
    'team-info' => $translate('Info'),
    'team-members' => $translate('Users'),
    'team-resources' => $translate('Resources'),
    'team-sites' => $translate('Sites'),
];
echo $this->sectionNav($sectionNavs, 'view.add.section_nav');
    $form = $this->form;
    $form->setAttribute('id', 'new_team');
    $form->prepare();
    echo $this->form()->openTag($form);
?>
    <fieldset id="team-info" class="section active">
        <?php echo $this->formCollection($form); ?>
    </fieldset>

<fieldset id="team-members" class="section">
    <?php echo $this->partial('teams/team/manage-users', [
        'team' => [],
        'bypass_teams_filter' => true,

    ]);
    ?>
</fieldset>

<?php
$itemsetForm = $this->itemsetForm;
$itemsetForm->prepare();
$formElement = $this->plugin('formElement');
echo $this->form()->openTag($itemsetForm);
?>
<fieldset id="team-resources" class="section">
    <div class="selection-criteria">
        <p>
            All items belonging to these item sets or owners will be added to the group
        </p>
        <div class="select-by-item-set-content">
            <?php echo $this->formCollection($itemsetForm->get('itemset')); ?>
        </div>
    </div>
</fieldset>

<fieldset id="team-sites" class="section">
    <div class="selection-criteria">
        <p>
            Attach sites to team.
        </p>
        <div class="select-by-item-set-content">
            <?php echo $this->formCollection($itemsetForm->get('site')); ?>
        </div>
    </div>
</fieldset>
<?php
echo $this->form()->closeTag();
else: ?>
    <?php $glob_admin_url = $this->hyperlink(
        'global admins',
        $this->url(
            'admin/default',
            [ 'controller' => 'user', 'action' => 'browse'],
            [
                'query' => [
                    'role' => 'global_admin',
                    'active' => '1',
                ],
            ]
        )
    ); ?>
    <div class="breadcrumbs">
    Only the <?php echo $glob_admin_url ?> can add new teams.
    </div>
<?php endif;
