<?php
$this->headScript()->appendFile($this->assetUrl('vendor/sortablejs/Sortable.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/site-resources.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/inject-removal-util-element.js', 'Teams'));
$this->headLink()->prependStylesheet($this->assetUrl('css/teams.css', 'Teams'));
$this->headScript()->appendFile($this->assetUrl('js/team-users.js', 'Teams'));

$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'teams add');
?>
<?php echo $this->pageTitle($translate('Add new team')); ?>
<?php $this->trigger('view.add.before'); ?>

<?php if ($this->roleAuth()->teamAuthorized('add', 'team')): ?>

<?php echo $this->partial('teams/team/edit-form', [
    'form'                    => $this->form,
    'resourceForm'            => $this->resourceForm,
    'secondaryResourcesForm'  => $this->secondaryResourcesForm,
    'sitesForm'               => $this->sitesForm,
    'team'                    => [],
    'bypassTeamFilterRoles'   => [],
    'user'                    => $this->identity(),
    'isAdd'                   => true,
]); ?>

<?php else: ?>
<?php $glob_admin_url = $this->hyperlink(
    $translate('global admins'),
    $this->url(
        'admin/default',
        ['controller' => 'user', 'action' => 'browse'],
        ['query' => ['role' => 'global_admin', 'active' => '1']]
    )
); ?>
<div class="breadcrumbs">
    <?php echo sprintf($translate('Only the %s can add new teams.'), $glob_admin_url); ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.add.after'); ?>

