<?php
$this->headScript()->appendFile($this->assetUrl('js/team-list-selector.js', 'Teams'));
$this->headLink()->appendStylesheet($this->assetUrl('css/teams.css', 'Teams'));
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle($translate('Teams')); ?>

<div id="page-actions">
<!--  for when ACL rules are in place  -->
    <?php if ($this->roleAuth()->teamAuthorized('add', 'team')): ?>
        <?php echo $this->hyperlink($translate('Add new team'), $this->url('admin/teams/add'), ['class' => 'button']); ?>
    <?php endif; ?>
</div>


<?php if ($this->current_team != "None"):?>
    <h2> Current Team: <?php echo $this->current_team->getName() ?></h2>
<?php else: ?>
    <h2> Current Team: You are Not Currently Assigned to a Team</h2>
<?php endif; ?>

<?php $this->trigger('view.browse.before'); ?>

<?php if ($this->user_teams): ?>
        <table class="tablesaw" data-tablesaw-mode="stack">
            <thead>
            <tr>
<!--                include below in the first <th> to include the Select All checkbox for batch edits -->
<!--                <input type="checkbox" class="select-all" aria-label="--><?php //echo $translate('Select all');?><!--">-->
                <th><?php echo $translate('Switch'); ?></th>
                <th><?php echo $translate('Team Name'); ?></th>
                <th></th>
                <th><?php echo $translate('Your Role'); ?></th>
                <th><?php echo $translate('Description'); ?></th>
                <th><?php echo $translate('Member Count'); ?></th>
                <th><?php echo $translate('Resource Count'); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->user_teams as $team):
                $team = $team->getTeam();
                if ($team->getId() == $this->current_team->getId()):?>
                    <tr class="team-option current-team">
                        <td>
                            <button class="fa fa-plus team-select" data-team-id="<?php echo $team->getId() ?>"></button>
                        </td>
                <?php else: ?>
                    <tr class="team-option">
                        <td>
                            <button class="fa fa-minus team-select" data-team-id="<?php echo $team->getId() ?>"></button>
                        </td>
                <?php endif; ?>
                <td>
                    <?php $current = $this->current_team->getId() == $team->getId() ?>
                    <?php $link_text = $this->current_team->getId() == $team->getId() ?>

                    <?php echo $this->hyperlink(
                            $team->getName(),
                            $this->url('admin/teams/detail', ['id' => $team->getId()])
                        )
                    ?>
                    </td>
                    <td>
                        <ul class="actions">
                            <?php if ($this->roleAuth()->teamAuthorized('update', 'team')): ?>
                            <li>
                                <a class="o-icon-edit" href="<?php echo $this->url('admin/teams/detail/update', ['id' => $team->getId()])?>"></a>
                            </li>
                                                        <?php endif; ?>
                            <?php if ($this->roleAuth()->teamAuthorized('delete', 'team')): ?>
                                <li><a class="o-icon-delete" href="<?php echo $this->url('admin/teams/detail/delete', ['id' => $team->getId()])?>"></a>
                                </li>
                            <?php endif; ?>
                            <li>
                                <a class="o-icon-more" href="<?php echo $this->url('admin/teams/detail', ['id' => $team->getId()])?>">    </a>
                            </li>
                        </ul>
                    </td>
                    <td>
                        <?php foreach ($team->getTeamUsers() as $user):

                            if ($user->getUser()->getId() == $this->identity()->getId()):
                                echo $user->getRole()->getName();
                            endif;

                        endforeach;?>
                    </td>
                    <td><?php echo $team->getDescription(); ?></td>
                    <td><a href="<?php echo $this->url('admin/teams/detail', ['id' => $team->getId()]) . '#users';?>"> <?php  echo count($team->getTeamUsers())?></td>
                    <td><a href="<?php echo $this->url('admin/teams/detail', ['id' => $team->getId()]) . '#team-resources';?>"> <?php echo count($team->getTeamResources()); ?></a></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

    </form>

<?php else: ?>

    <div class="no-resources o-icon-users">
        <p><?php echo $translate('Omeka could not find any teams you belong to.'); ?></p>
    </div>

<?php endif; ?>




