<?php
//Deprecated. this was used for Omeka 2.x and is kept for reference when building a more useful Omeka 3.x site/resources page

$translate = $this->plugin('translate');
$form->prepare();
$this->headScript()->appendFile($this->assetUrl('vendor/sortablejs/Sortable.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/site-item-sets.js', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'sites resources');

$rowTemplate = '
<tr class="site-item-set-row">
    <td class="sortable-handle"></td>
    <td class="site-item-set-title"></td>
    <td class="site-item-set-owner-email"></td>
    <td>
' . $this->hyperlink('', '#', ['class' => 'o-icon-delete', 'title' => $translate('Remove item set')])
    . '<input type="hidden" class="site-item-set-id" name="o:site_item_set[][o:item_set][o:id]">
    </td>
</tr>';
?>
<div><p>Item pools are functionally replaced by the Teams module. But you still must select the item sets you'd
        like to show up in in the "Browse by Item Set" block.</p>

</div>
<?php echo $this->pageTitle($translate('Resources'), 1, $translate('Sites')); ?>
<?php echo $this->sectionNav([
    'item-pool-section' => $translate('Item pool'),
    'item-sets-section' => $translate('Item sets'),
]); ?>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formCollection($form, false); ?>

<div id="page-actions">
    <?php echo $this->cancelButton(); ?>
    <button><?php echo $translate('Save'); ?></button>
</div>

<div id="item-pool-section" class="active section">
    <p><?php echo sprintf(
    $this->translate('There are currently %s resources that this site has access to, contributed by these teams: '),


            //TODO either this should link to a new view that has the site's resources (an acl nightmare) or shouldn't link
            count($this->site_items)
); ?></p>
    <ul>
        <?php foreach ($this->site_teams as $site_team):
            ?><li><?php echo $site_team->getTeam()->getName(); ?></li><?php         endforeach;
        ?>
    </ul>
    <p>View these resources in the
        <?php echo $this->hyperlink('Item', $this->url('admin', ['item'])); ?>,
        <?php echo $this->hyperlink('Item set', $this->url('admin', ['item-set'])); ?>, and
        <?php echo $this->hyperlink('Media', $this->url('admin', ['media'])); ?>
        pages

    </p>
</div>

<div id="item-sets-section" class="section">
<p>This only controls what item sets are displayed in the "Browse by Item Set" Block</p>
    <table id="site-item-sets" class="tablesaw tablesaw-stack"
           data-tablesaw-mode="stack"
           data-item-sets="<?php echo $this->escapeHtml(json_encode($itemSets)); ?>"
           data-row-template="<?php echo $this->escapeHtml($rowTemplate); ?>">
        <thead>
        <tr>
            <th></th>
            <th><?php echo $translate('Title'); ?></th>
            <th><?php echo $translate('Owner'); ?></th>
            <th></th>
        </tr>
        </thead>
        <tbody id="site-item-set-rows"></tbody>
    </table>
    <p id="no-site-item-sets"><?php echo $translate('No item sets are assigned to this site.'); ?></p>
    <?php echo $this->itemSetSelector(true); ?>
</div>

<?php echo $this->form()->closeTag(); ?>
