<?php
$role = $this->role;
$team_users = $this->team_users;
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'items show');

$sectionNavs = [
    'item-metadata' => $translate('Info'),
    'item-linked' => $translate('Permissions'),
    'role-users' => $translate('Users'),
]; ?>

<?php echo $this->pageTitle("Team Role: " . $role->getName()); ?>
<?php echo $this->sectionNav($sectionNavs, 'view.show.section_nav', $role); ?>

<div id="page-actions">
    <?php if ($this->roleAuth()->teamAuthorized('delete', 'role')): ?>
        <a class="button" href="<?php echo $this->url('admin/teams/roles/detail/delete', ['id' => $role->getId()]) ?>">
            Delete role </a>
    <?php endif; ?>
</div>

<div id="item-metadata" class="active section">
    <dl>
        <div class="property">
            <dt><?php echo $translate('Name'); ?></dt>
            <dd class="value">
                <span class="value-content"><?php echo $escape($role->getName()); ?></span>
            </dd>
        </div>
        <div class="property">
            <dt><?php echo $translate('Description'); ?></dt>
            <dd class="value">
                <span class="value-content"><?php echo $escape($role->getComment()); ?></span>
            </dd>
        </div>
    </dl>
</div>

<div id="item-linked" class="section">
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
        <tr>
            <th><?php echo $translate('Add Team Members?'); ?></th>
            <th><?php echo $translate('Add Resources?'); ?></th>
            <th><?php echo $translate('Modify Site?'); ?></th>
            <th><?php echo $translate('Modify Team Resources?'); ?></th>
            <th><?php echo $translate('Delete Team Resources?'); ?></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><input type="checkbox" disabled <?php if ($role->getCanAddUsers()) { ?> checked <?php } ?>></td>
            <td><input type="checkbox" disabled <?php if ($role->getCanAddItems()) { ?> checked<?php } ?>></td>
            <td><input type="checkbox" disabled <?php if ($role->getCanAddSitePages()) { ?> checked<?php } ?>></td>
            <td><input type="checkbox" disabled <?php if ($role->getCanModifyResources()) { ?> checked<?php } ?>></td>
            <td><input type="checkbox" disabled <?php if ($role->getCanDeleteResources()) { ?> checked<?php } ?>></td>
        </tr>
        </tbody>
    </table>
</div>

<div id="role-users" class="section">
    <?php $teams = $this->api()->search('team')->getContent(); ?>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
        <tr>
            <th><?php echo $translate('Team'); ?></th>
            <th><?php echo $translate('Users with ' . $role->getName() . ' role'); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($teams as $team): ?>
            <tr>
                <td><?php echo $team->name() ?></td>
                <td>
                    <ul>
                        <?php if (array_key_exists($team->name(), $team_users)):
                            foreach ($team_users[$team->name()] as $user): ?>
                                <li>
                                    <?php echo
                                    $this->hyperlink(
                                        $user->getName(),
                                        $this->url('admin/id', ['controller' => 'user', 'id' => $user->getId()])
                                    ); ?>
                                </li>
                               <?php endforeach; ?>
                         <?php endif; ?>
                    </ul>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
