<?php
$role = $this->response->getContent();
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$resourceSortHeadings = [
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title'
    ],
    [
        'label' => $translate('Identifier'),
        'value' => 'dcterms:identifier'
    ],
    [
        'label' => $translate('Class'),
        'value' => 'resource_class_label'
    ],
    [
        'label' => $translate('Owner'),
        'value' => 'owner_name'
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created'
    ],
];


$sectionNavs = [
    'item-metadata' => $translate('Info'),
    'item-linked' => $translate('Permissions'),
    'role-users' => $translate('Users'),
];
?>
<?php echo $this->pageTitle("Team Role: " . $role->name()); ?>

<?php echo $this->sectionNav($sectionNavs, 'view.show.section_nav', $role); ?>




<div id="page-actions">

    <?php if ($this->roleAuth()->teamAuthorized('delete', 'role')): ?>
        <a class="button" href="<?php echo $this->url('admin/teams/roles/detail/delete', ['id' => $role->id()])?>"> Delete Role </a>
    <?php endif; ?>
</div>



<div id="item-metadata" class="active section">
    <div class="meta-group">
        <h4><?php echo $translate('Name'); ?></h4>
        <div class="value"><?php echo $escape($role->name()); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $translate('Comment'); ?></h4>
        <div class="value"><?php echo $escape($role->getComment()); ?></div>
    </div>



</div>


<div id="item-linked" class="section">

    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
        <tr>
            <!--                include below in the first <th> to include the Select All checkbox for batch edits -->
            <!--                <input type="checkbox" class="select-all" aria-label="--><?php //echo $translate('Select all'); ?><!--">-->
            <th><?php echo $translate('Add Team Members?'); ?></th>
            <th><?php echo $translate('Add Items?'); ?></th>
            <th><?php echo $translate('Add Item Sets?'); ?></th>
            <th><?php echo $translate('Modify Site?'); ?></th>
            <th><?php echo $translate('Modify Team Resources?'); ?></th>
            <th><?php echo $translate('Delete Team Resources?'); ?></th>

        </tr>
        </thead>
        <tbody>

            <tr>



                <td><input type="checkbox" disabled <?php if($role->canAddUsers()){?> checked <?php }; ?>></td>
                <td><input type="checkbox" disabled <?php if($role->canAddItems()){?> checked<?php }; ?>></td>
                <td><input type="checkbox" disabled <?php if($role->canAddItemsets()){?> checked<?php }; ?>></td>
                <td><input type="checkbox" disabled <?php if($role->canAddSitePages()){?> checked<?php }; ?>></td>
                <td><input type="checkbox" disabled <?php if($role->canModifyResources()){?> checked<?php }; ?>></td>
                <td><input type="checkbox" disabled <?php if($role->canDeleteResources()){?> checked<?php }; ?>></td>




            </tr>
        </tbody>
    </table>



</div>

<div id="role-users" class="section">
    <?php $teams = $this->api()->search('team')->getContent();

    ?>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
        <tr>
            <!--                include below in the first <th> to include the Select All checkbox for batch edits -->
            <!--                <input type="checkbox" class="select-all" aria-label="--><?php //echo $translate('Select all'); ?><!--">-->
            <th><?php echo $translate('Team'); ?></th>
            <th><?php echo $translate('Users with '. $role->name() . ' role'); ?></th>

        </tr>
        </thead>
        <tbody>




<?php foreach ($teams as $team):
?>
    <tr>
    <td><?php echo $team->name()?></td>
    <td><ul>
        <?php $team_users = $team->users();
        $key = array_search($role->name(), array_column(array($team_users), 'role'));
        foreach ($team_users as $team_user):
            if ($team_user->getRole()->getName() == $role->name()){

        ?><li>
                <a href="<?php echo $this->url('admin/id', ['controller'=> 'user', 'id' =>  $team_user->getUser()->getId() ]) ?>">
                    <?php echo $team_user->getUser()->getName(); ?></a> <?php             };
        ?></li><?php         endforeach;

        ?>
        </ul>
    </td>
    </tr>

<?php endforeach;
?>

        </tbody>
    </table>


</div>
