<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

?>

<?php echo $this->pageTitle($translate('Team Roles')); ?>


<div id="page-actions">
    <!--  for when ACL rules are in place  -->
        <?php if ($this->roleAuth()->teamAuthorized('add', 'role')): ?>
    <?php echo $this->hyperlink($translate('Add new role'), $this->url('admin/teams/roles/add'), ['class' => 'button']); ?>
        <?php endif; ?>
</div>
<?php
$response = $this->response;

?>


<h3><?php echo $this->setting('installation_title') . ' Team Roles'; ?>:</h3>


<?php if ($this->response): ?>

    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
        <tr>
            <!--                include below in the first <th> to include the Select All checkbox for batch edits -->
            <!--                <input type="checkbox" class="select-all" aria-label="--><?php //echo $translate('Select all'); ?><!--">-->
            <th><?php echo $translate('Role Name'); ?></th>
            <th><?php echo $translate('Teams Where You Have This Role'); ?></th>
            <th><?php echo $translate('Add Team Members?'); ?></th>
            <th><?php echo $translate('Add Resources?'); ?></th>
            <th><?php echo $translate('Modify Site?'); ?></th>
            <th><?php echo $translate('Modify Team Resources?'); ?></th>
            <th><?php echo $translate('Delete Team Resources?'); ?></th>

        </tr>
        </thead>
        <tbody>
        <?php foreach ($response as $role): ?>

            <tr>
                <td>
                    <a href="<?php echo $this->url('admin/teams/roles/detail', ['id'=> $role->getId()])?>">
                    <?php echo $role->getName()?></a>
                </td>
                <td>
                    <ul>

                    <?php foreach ( $role->getTeamUsers() as $roleUser):
                        if ($roleUser->getUser()->getId() == $this->identity()->getId()){
                            ?>

                       <li>
                        <a href="<?php echo $this->url('admin/teams/detail', [ 'id' => $roleUser->getTeam()->getId()]) ?>">
                            <?php                             echo $roleUser->getTeam()->getName();?>
                            </a> </li><?php                         }

                    endforeach;
                    ?>
                    </ul>
                </td>

                <td><input type="checkbox" disabled <?php if($role->getCanAddUsers()){?> checked <?php }; ?>></td>
                <td><input type="checkbox" disabled <?php if($role->getCanAddItems()){?> checked<?php }; ?>></td>
                <td><input type="checkbox" disabled <?php if($role->getCanAddSitePages()){?> checked<?php }; ?>></td>
                <td><input type="checkbox" disabled <?php if($role->getCanModifyResources()){?> checked<?php }; ?>></td>
                <td><input type="checkbox" disabled <?php if($role->getCanDeleteResources()){?> checked<?php }; ?>></td>




            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    </form>




<?php else: ?>

    <div class="no-resources">
        <p><?php echo $translate('Omeka could not find any roles.'); ?></p>
    </div>

<?php endif; ?>




