<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

?>

<?php echo $this->pageTitle($translate('Team Roles')); ?>

<!--variable passed in from the controller-->
<?php //echo $this->searchFilters(); ?>

<div class="browse-controls">
    <!--    --><?php //echo $this->pagination(); ?>
    <!--    --><?php //echo $this->hyperlink($translate('Advanced search'), $this->url(null, ['action' => 'search'], ['query' => $this->params()->fromQuery()], true), ['class' => 'advanced-search']); ?>
    <!--    --><?php //echo $this->sortSelector($sortHeadings); ?>
</div>

<div id="page-actions">
    <!--  for when ACL rules are in place  -->
    <!--    --><?php //if ($this->userIsAllowed('Omeka\Api\Adapter\ItemAdapter', 'create')): ?>
    <?php echo $this->hyperlink($translate('Add new role'), $this->url('admin/teams/roles/add'), ['class' => 'button']); ?>
    <!--    --><?php //endif; ?>
</div>








<?php
$response = $this->response;
//$current_role_users = $this->api()->read('role', ['id'=>1])->getContent()->users();
//$current_role_id = $this->api()->read('role-user', ['id'=>1])->getContent()->roleId();
//$current_role = $this->api()->read('role', ['id'=>$current_role_id])->getContent()->name();
?>

<!--<h1>Roles</h1>-->

<h3><?php echo $this->setting('installation_title') . ' Team Roles'; ?>:</h3>


<?php if ($this->response): ?>
    <!--    <form method="post" id="batch-form" class="disable-unsaved-warning">-->
    <!--        --><?php //if ($this->userIsAllowed('Omeka\Api\Adapter\ItemAdapter', 'batch_update')): ?>
    <!--            <div class="batch-inputs">-->
    <!--                <select class="batch-actions-select" aria-label="--><?php //echo $translate('Batch actions'); ?><!--">-->
    <!--                    <option value="default">--><?php //echo $translate('Batch actions'); ?><!--</option>-->
    <!--                    <option value="update-selected" disabled="true">--><?php //echo $translate('Edit selected'); ?><!--</option>-->
    <!--                    <option value="update-all">--><?php //echo $translate('Edit all'); ?><!--</option>-->
    <!--                    <option value="delete-selected" disabled="true">--><?php //echo $translate('Delete selected'); ?><!--</option>-->
    <!--                    <option value="delete-all">--><?php //echo $translate('Delete all'); ?><!--</option>-->
    <!--                </select>-->
    <!--                <div class="batch-actions">-->
    <!--                    <button type="button" class="default active" disabled="true">--><?php //echo $translate('Go'); ?><!--</button>-->
    <!--                    <input type="submit" class="update-selected" name="update_selected" value="--><?php //echo $translate('Go'); ?><!--" formaction="--><?php //echo $escape($this->url(null, ['action' => 'batch-edit'], true)); ?><!--">-->
    <!--                    <input type="submit" class="update-all" name="update_all" value="--><?php //echo $translate('Go'); ?><!--" formaction="--><?php //echo $escape($this->url(null, ['action' => 'batch-edit-all'], true)); ?><!--">-->
    <!--                    <input type="hidden" name="query" class="batch-query" value="--><?php //echo $escape(json_encode($this->params()->fromQuery())); ?><!--">-->
    <!--                    <a class="delete button sidebar-content delete-selected" data-sidebar-selector="#sidebar-delete-selected">--><?php //echo $translate('Go'); ?><!--</a>-->
    <!--                    <a class="delete button sidebar-content delete-all" data-sidebar-selector="#sidebar-delete-all">--><?php //echo $translate('Go'); ?><!--</a>-->
    <!--                </div>-->
    <!--            </div>-->
    <!--        --><?php //endif; ?>

    <!--add class batch-edit if including the batch edit code from above-->
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
        <tr>
            <!--                include below in the first <th> to include the Select All checkbox for batch edits -->
            <!--                <input type="checkbox" class="select-all" aria-label="--><?php //echo $translate('Select all'); ?><!--">-->
            <th><?php echo $translate('Role Name'); ?></th>
            <th><?php echo $translate('Teams Where You Have This Role'); ?></th>
            <th><?php echo $translate('Add Team Members?'); ?></th>
            <th><?php echo $translate('Add Items?'); ?></th>
            <th><?php echo $translate('Add Item Sets?'); ?></th>
            <th><?php echo $translate('Modify Site?'); ?></th>
            <th><?php echo $translate('Modify Team Resources?'); ?></th>
            <th><?php echo $translate('Delete Team Resources?'); ?></th>

        </tr>
        </thead>
        <tbody>
        <?php foreach ($response as $role): ?>

            <tr>
                <td>
                    <!--                        un comment to include checkbox for batch editing -->
                    <!--                        --><?php //if ($role->userIsAllowed('update') || $role->userIsAllowed('delete')): ?>
                    <!--                            <input type="checkbox" name="resource_ids[]" value="--><?php //echo $role->id(); ?><!--" aria-label="--><?php //echo $translate('Select role'); ?><!--">-->
                    <!--                        --><?php //endif; ?>
                    <!--                        --><?php //echo $role->linkPretty(); ?>
                    <!--                        --><?php //if (!$role->isPublic()): ?>
                    <!--                            <span class="o-icon-private" aria-label="--><?php //echo $translate('Private'); ?><!--"></span>-->
                    <!--                        --><?php //endif; ?>
                    <a href="<?echo $this->url('admin/teams/roles/detail', ['id'=> $role->getId()])?>">
                    <?php echo $role->getName()?></a>
                </td>
                <td>
                    <ul>

                    <?php foreach ( $role->getTeamUsers() as $roleUser):
                        if ($roleUser->getUser()->getId() == $this->identity()->getId()){
                            ?>

                       <li>
                        <a href="<?php echo $this->url('admin/teams/detail', [ 'id' => $roleUser->getTeam()->getId()]) ?>">
                            <?
                            echo $roleUser->getTeam()->getName();?>
                            </a> </li><?
                        }

                    endforeach;
                    ?>
                    </ul>
                </td>

                <td><input type="checkbox" disabled <?php if($role->getCanAddUsers()){?> checked <?}; ?>></td>
                <td><input type="checkbox" disabled <?php if($role->getCanAddItems()){?> checked<?}; ?>></td>
                <td><input type="checkbox" disabled <?php if($role->getCanAddItemsets()){?> checked<?}; ?>></td>
                <td><input type="checkbox" disabled <?php if($role->getCanAddSitePages()){?> checked<?}; ?>></td>
                <td><input type="checkbox" disabled <?php if($role->getCanModifyResources()){?> checked<?}; ?>></td>
                <td><input type="checkbox" disabled <?php if($role->getCanDeleteResources()){?> checked<?}; ?>></td>




            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    </form>

    <?php $this->trigger('view.browse.after'); ?>
    <div class="browse-controls">
        <?php echo $this->pagination(); ?>
    </div>

    <div id="sidebar" class="sidebar">
        <?php echo $this->hyperlink('', '#', [
            'class' => 'sidebar-close o-icon-close',
            'title' => $translate('Close'),
        ]); ?>
        <div class="sidebar-content"></div>
    </div>
    <div id="sidebar-delete-selected" class="sidebar">
        <?php echo $this->hyperlink('', '#', [
            'class' => 'sidebar-close o-icon-close',
            'title' => $translate('Close'),
        ]); ?>
        <div class="sidebar-content">
            <div id="sidebar-confirm">
                <h3><?php echo $translate('Delete items'); ?></h3>
                <p><?php echo $translate('Are you sure you would like to delete the selected items?'); ?></p>
                <p class="error"><?php echo sprintf(
                        $translate('%s: this action will permanently delete %s items and cannot be undone.'),
                        sprintf('<strong>%s</strong>', $translate('Warning')),
                        '<strong><span id="delete-selected-count"></span></strong>'
                    ); ?></p>
                <!--                --><?php //echo $this->form($this->formDeleteSelected); ?>
            </div>
        </div>
    </div>
    <div id="sidebar-delete-all" class="sidebar">
        <?php echo $this->hyperlink('', '#', [
            'class' => 'sidebar-close o-icon-close',
            'title' => $translate('Close'),
        ]); ?>
        <div class="sidebar-content">
            <div id="sidebar-confirm">
                <h3><?php echo $translate('Delete items'); ?></h3>
                <p><?php echo $translate('Are you sure you would like to delete all items on all pages of this result?'); ?></p>
                <p class="error"><?php echo sprintf(
                        $translate('%s: this action will permanently delete %s items and cannot be undone.'),
                        sprintf('<strong>%s</strong>', $translate('Warning')),
                        sprintf('<strong>%s</strong>', number_format($this->pagination()->getPaginator()->getTotalCount()))
                    ); ?></p>
                <label><input type="checkbox" name="confirm-delete-all-check"> <?php echo $translate('Are you sure?'); ?></label>
                <!--                --><?php //echo $this->form($this->formDeleteAll); ?>
            </div>
        </div>
    </div>

    <script>
        // Complete the batch delete form after confirmation.
        $('#confirm-delete-selected, #confirm-delete-all').on('submit', function(e) {
            var confirmForm = $(this);
            if ('confirm-delete-all' === this.id) {
                confirmForm.append($('.batch-query').clone());
            } else {
                $('#batch-form').find('input[name="resource_ids[]"]:checked').each(function() {
                    confirmForm.append($(this).clone().prop('disabled', false).attr('type', 'hidden'));
                });
            }
        });
        $('.delete-all').on('click', function(e) {
            Omeka.closeSidebar($('#sidebar-delete-selected'));
        });
        $('.delete-selected').on('click', function(e) {
            Omeka.closeSidebar($('#sidebar-delete-all'));
            var inputs = $('input[name="resource_ids[]"]');
            $('#delete-selected-count').text(inputs.filter(':checked').length);
        });
        $('#sidebar-delete-all').on('click', 'input[name="confirm-delete-all-check"]', function(e) {
            $('#confirm-delete-all input[type="submit"]').prop('disabled', this.checked ? false : true);
        });
    </script>

<?php else: ?>

    <div class="no-resources">
        <p><?php echo $translate('Omeka could not find any items.'); ?></p>
    </div>

<?php endif; ?>




