<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$roles = $this->roles;
$user_roles = $this->user_roles;
?>

<?php echo $this->pageTitle($translate('Team Roles')); ?>

<div id="page-actions">
        <?php if ($this->roleAuth()->teamAuthorized('add', 'role')): ?>
            <?php echo
            $this->hyperlink(
                $translate('Add new role'),
                $this->url('admin/teams/roles/add'),
                ['class' => 'button']
            );
            endif; ?>
</div>

<h3><?php echo $this->setting('installation_title') . ' Team Roles'; ?>:</h3>

<?php if ($this->roles): ?>

    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
        <tr>
            <!--                include below in the first <th> to include the Select All checkbox for batch edits -->
            <!--                <input type="checkbox" class="select-all" aria-label="--><?php //echo $translate('Select all');?><!--">-->
            <th><?php echo $translate('Role Name'); ?></th>
            <th><?php echo $translate('Teams Where You Have This Role'); ?></th>
            <th><?php echo $translate('Add Team Members?'); ?></th>
            <th><?php echo $translate('Add Resources?'); ?></th>
            <th><?php echo $translate('Modify Site?'); ?></th>
            <th><?php echo $translate('Modify Team Resources?'); ?></th>
            <th><?php echo $translate('Delete Team Resources?'); ?></th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($roles as $role): ?>
            <tr>
                <td>
                    <?php echo $this->hyperlink(
                $role->getName(),
                $this->url(
                    'admin/teams/roles/detail',
                    ['id' => $role->getId()]
                )
            ); ?>
                </td>
                <td>
                    <?php if (array_key_exists($role->getName(), $user_roles)): ?>
                    <ul>
                        <?php foreach ($user_roles[$role->getName()] as $team): ?>
                        <li>
                            <?php echo
                            $this->hyperlink(
                                $team->getName(),
                                $this->url('admin/teams/detail', [ 'id' => $team->getId()])
                            ); ?>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                    <?php endif; ?>
                </td>
                <td><input type="checkbox" disabled <?php if ($role->getCanAddUsers()) {?> checked <?php } ?>></td>
                <td><input type="checkbox" disabled <?php if ($role->getCanAddItems()) {?> checked<?php } ?>></td>
                <td><input type="checkbox" disabled <?php if ($role->getCanAddSitePages()) {?> checked<?php } ?>></td>
                <td><input type="checkbox" disabled <?php if ($role->getCanModifyResources()) {?> checked<?php } ?>></td>
                <td><input type="checkbox" disabled <?php if ($role->getCanDeleteResources()) {?> checked<?php } ?>></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

<?php  else: ?>

    <div class="no-resources">
        <p><?php echo $translate('Omeka could not find any roles.'); ?></p>
    </div>

<?php endif; ?>