<?php
$team = $this->response->getContent();
?>

<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'items show');
$resourceSortHeadings = [
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title',
    ],
    [
        'label' => $translate('Identifier'),
        'value' => 'dcterms:identifier',
    ],
    [
        'label' => $translate('Class'),
        'value' => 'resource_class_label',
    ],
    [
        'label' => $translate('Owner'),
        'value' => 'owner_name',
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created',
    ],
];

$sectionNavs = [
    'item-metadata' => $translate('Info'),
    'users' => $translate('Users'),
    'team-resources' => $translate('Resources'),
];
?>

<?php echo $this->pageTitle("Team: " . $team->name()); ?>

<?php echo $this->sectionNav($sectionNavs, 'view.show.section_nav', $team); ?>
<div id="page-actions">
    <?php if ($this->roleAuth()->teamAuthorized('update', 'team_user')): ?>
        <a class="button" href="<?php echo $this->url('admin/teams/detail/update', ['id' => $team->id()])?>"> Edit team </a>
    <?php endif; ?>
</div>
<div id="item-metadata" class="active section">
    <dl>
        <div class="property">
            <dt><?php echo $translate('Name'); ?></dt>
            <dd class="value">
                <span class="value-content"><?php echo $escape($team->name()); ?></span>
            </dd>
        </div>
        <div class="property">
            <dt><?php echo $translate('Description'); ?></dt>
            <dd class="value">
                <span class="value-content"><?php echo $escape($team->description()); ?></span>
            </dd>
        </div>
        <div class="property">
            <dt>Linked Sites</dt>
            <dd class="value">
                <span class="value-content">
                    <?php foreach ($team->sites() as $site):?>
                        <?php echo $site->title(); ?>
                        <?php echo '<br>' ?>
                    <?php endforeach; ?>
                </span>
            </dd>
        </div>
    </dl>
</div>

<div id="users" class="section">

    <?php if (count($team->teamUsers()) > 0): ?>
                   <table class="tablesaw batch-edit" data-tablesaw-mode="stack">
                <thead>
                    <tr>
                        <th><?php echo $translate('Name'); ?></th>
                        <th><?php echo $translate('Role'); ?></th>
                        <th><?php echo $translate('Last active in this team'); ?></th>
                    </tr>
                </thead>
                <tbody>

        <?php foreach ($team->teamUsers() as $team_user):?>
                    <tr>
                        <td>
                            <?php echo $this->hyperlink(
                                    $team_user->getUser()->getName(),
                                    $this->url('admin/id', ['controller' => 'user', 'id' => $team_user->getUser()->getId() ])
                            ) ?>
                        </td>
                        <td><?php echo $team_user->getRole()->getName(); ?></td>
                        <?php if ($team_user->getCurrent()): ?>
                            <td>Yes</td>
                        <?php else: ?>
                            <td>No</td>
                        <?php endif; ?>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
    <?php else: ?>
        <div class="no-resources o-icon-users">
            <p><?php echo $translate('No users currently belong to this team.'); ?></p>
        </div>
    <?php endif; ?>


</div>

<div id="team-resources" class="section">
        <form method="post" id="batch-form" class="disable-unsaved-warning">
            <table class="tablesaw" data-tablesaw-mode="stack">
                <thead>
                    <tr>
                        <th><?php echo $translate('Resource Type'); ?></th>
                        <th><?php echo $translate('Count'); ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->resources as $key => $values):?>
                    <tr>
                        <td>
                            <?php echo $key;?>
                        </td>
                        <td>
                            <?php echo $values['count']?>
                        </td>
                    </tr>
                    <?php endforeach;?>
                </tbody>
            </table>
        </form>
</div>








