<?php
$role = array();
$team = array();
foreach ($this->user_teams as $tu):
    $role[] = $tu->getRole()->getId();
    $team[] = $tu->getTeam()->getId();

endforeach;

?>

<script>

    window.addEventListener("load", function () {


        let current_teams = <?php echo json_encode($team)?>;
        let current_roles = <?php echo json_encode($role)?>;


        let select = document.getElementById('team');

        for (let i=0; i < select.options.length; i++){
            for (let j=0; j < current_teams.length; j++){
                if (current_teams[j] == select.options[i].value){
                    select.options[i].setAttribute('selected', true);
                    makeRoleElement(select.options[i].innerText, current_teams[j], current_roles[j])
                }
            }
        }
        $("#team").trigger("chosen:updated");
    });
</script>