<?php $this->headScript()->captureStart() ?>
<?php $this->headScript()->captureEnd();
?>
<?php
if ($this->team_ids == null) {
    ?>
    <script>
        window.addEventListener("load", function () {
            $('button:contains("Add")').prop("disabled",true);

        });

    </script>
    <?php
} else {
        ?>
    <script>
        window.addEventListener("load", function () {


            let current_teams = <?php echo $this->team_ids?>;


            let select = document.getElementById('team_selected');

            for (let i = 0; i < select.options.length; i++) {
                if (current_teams == select.options[i].value) {
                    select.options[i].setAttribute('selected', true);
                }
            }
            $("select#team_selected").trigger("chosen:updated");

        });

    </script>
    <?php
    }
