<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'add items');
?>

<?php echo $this->pageTitle($translate('New team'), 1, $translate('Teams')); ?>
<?php $this->trigger('view.add.before'); ?>
<?php
echo $this->partial('teams/team/form.phtml', [
    'itemSetForm' => $itemSetForm,
    'teamForm' => $teamForm,
    'submitLabel' => 'Create Team',
    'action' => 'add',
    'users' => $this->users,
]);
?>

<?php $this->trigger('view.add.after'); ?>
