<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$formLabel = $this->plugin('formLabel');
$formElement = $this->plugin('formElement');
$none = null;
?>

<?php echo $this->form()->openTag($teamForm); ?>

<?php echo $this->sectionNav([
    'info' => $translate('Info'),
    'users' => $translate('Users'),
    'resources' => $translate('Resources'),
    'sites' => $translate('Sites'),
]); ?>

<?php $this->trigger("view.$action.form.before", ['form' => $teamForm]); ?>

<fieldset id="info" class="section active" aria-labelledby="info-label">
    <?php echo $this->formCollection($teamForm); ?>
</fieldset>

<fieldset id="users" class="section" aria-labelledby="users-label">
    <?php echo $this->partial('teams/team/manage-users', [
        'team' => $this->team,

    ]);
    ?>
</fieldset>

<fieldset id="resources" class="section" aria-labelledby="resources-label">
    <?php echo $this->partial('teams/team/manage-resources', [
        'none' => $none,
    ]); ?>
</fieldset>

<fieldset id="sites" class="section" aria-labelledby="sites-label">
    <?php echo $this->partial('teams/team/manage-sites', [
        'team' => $none,
    ]); ?>
</fieldset>

<div id="page-actions">
    <?php echo (isset($deleteButton)) ? $deleteButton : ''; ?>
    <?php echo $this->cancelButton(); ?>
    <button type="submit" name="add-team-submit"><?php echo $escape($submitLabel); ?></button>
</div>

<?php $this->trigger("view.$action.form.after", ['form' => $teamForm]); ?>

<?php echo $this->form()->closeTag(); ?>

<?php echo $this->partial('common/resource-form-templates.phtml'); ?>
