<?php
$escape = $this->plugin('escapeHtml');

// Teams are already sorted.
$teamsByInitial = [];
$totalCount = 0;
foreach ($this->teams as $team) {
    if ($this->roleAuth()->teamAuthorized('add', 'resource', $team->id())) {
        $totalCount+=1;
        if (extension_loaded('mbstring')) {
            $initial = mb_substr($team->name(), 0, 1);
            $teamsByInitial[mb_strtolower($initial)][] = $team;
        } else {
            $initial = substr($team->name(), 0, 1);
            $teamsByInitial[strtolower($initial)][] = $team;
        }
    }
}

?>
<div id="team-selector" class='selector sidebar active'>
    <a href="#" class="mobile-only sidebar-close o-icon-close"><span class="screen-reader-text"><?php echo $this->translate('Close Me'); ?></span></a>
    <h3><?php echo $this->translate('Click on a team to add it to the edit panel.'); ?></h3>
    <input type="text" class="selector-filter" placeholder="<?php echo $escape($this->translate('Filter teams')); ?>">
    <ul>
        <li class="total-count-heading"><?php echo $this->translate('All teams'); ?> (<span class="selector-total-count"><?php echo $totalCount; ?></span>)
            <ul class="selectable-list">
                <?php foreach ($teamsByInitial as $initial => $teams): ?>
                <li class="selector-parent">
                    <span><?php echo $initial; ?></span>
                    (<span class="selector-child-count"><?php echo count($teamsByInitial[$initial]); ?></span>)
                    <ul>
                        <?php foreach ($teams as $team): ?>
                            <li class="selector-child" data-child-search="<?php echo $escape($team->name()); ?>" data-team-internal-id="<?php echo $escape($team->id()); ?>">
                                <span><?php echo $escape($team->name()); ?></span>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                    <?php endforeach; ?>
            </ul>
        </li>
    </ul>
</div>
