<style>
    .team-no-teams {
        text-align: center;
        position: relative;
        margin-top:96px
    }

    .team-no-teams:before {
        font-family: "Font Awesome 5 Free";
        font-weight: 900;
        font-size: 96px;
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        opacity:.08
    }

    .team-no-teams p {
        font-size: 24px;
        line-height: 48px;
        margin-top:48px}

    .team-no-teams:before{
        content: "\f0c0"
                     }


</style>

<?php
$org_unit = 'teams';
$resource_type = $this->resource_type;


if ($this->teams) {
    ?><p><?php echo $this->translate(sprintf('The following %s are linked to this %s', $org_unit, $resource_type)); ?></p><?php
    ?><ul><?php     foreach ($this->teams as $team):
        ?>
   <li><a href="<?php echo $this->url('admin/teams/detail', ['id'=> $team->getId()])?>">
    <?php echo $team->getName(); ?>
    </a></li>
    <?php endforeach; ?></ul><?php
} else { ?>
<div class="team-no-teams">
<p><?php echo $this->translate(sprintf('No teams are linked to this %s', $resource_type));; ?></p>
</div>
<?php } ?>
