<script>
    switchTeamHref = "<?php echo $this->url('admin/teams')?>";

    <?php if ($this->current_team == 'None') { ?>
        teamName = "No Team Assigned";
        viewTeam = "<?php echo $this->url('admin/teams') ?>";
    <?php

    } else {
        ?>
            teamName = "<?php echo $this->current_team->getName()?>";
            viewTeamHref = "<?php echo $this->url('admin/teams/detail', ['id'=>$this->current_team->getId()]) ?>";
            editTeamHref = "<?php echo $this->url('admin/teams/detail/update', ['id'=>$this->current_team->getId()]) ?>";

        <?php
    }
    ?>
</script>