<div>

    <select id="team_options" name="team_id" >

            <? if ($this->current_team == null){
                echo 'Current Team is Null';
                foreach ($this->user_teams as $team):
                    ?><option value="<?echo $team->getTeam()->getId();?>"><? echo $team->getTeam()->getName();?></option><?
                endforeach;
                ?> <option value="null" selected>None</option><?
            } else {

                foreach ($this->user_teams as $team):
                    ?>
                    <option <? if ($team->getTeam()->getName() == $this->current_team){ ?>selected <?
                } ?>value="<? echo $team->getTeam()->getId(); ?>"><? echo $team->getTeam()->getName(); ?></option><?
                endforeach;

            }?>

        </select>
</div>

<?php //$this->items = null;