<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/teams.css', 'Teams'));
$this->headScript()->appendFile($this->assetUrl('js/add-team-to-resource.js', 'Teams'));

$escape = $this->plugin('escapeHtml');
$removeStr = $escape($this->translate('Remove team'));

//controls how teams added to list appear
$teamTemplate = '
<tr>
    <td class="team-name"></td>
    <td>
        <ul class="actions">
            <li>
                <a href="#" class="o-icon-delete new" title="' . $removeStr . '" aria-label="' . $removeStr . '"></a>
            </li>
        </ul>
        <input type="hidden" name="add_team[]">
    </td>
</tr>';
?>
<fieldset id="teams" class="section team" aria-labelledby="teams-label" form="add-item">
    <legend id="teams-legend"><?php echo $this->translate('Teams'); ?></legend>
    <table id="team-resources" data-tablesaw-mode="stack" class="tablesaw tablesaw-stack <?php echo ($resource && $teams) ? '' : 'empty'; ?>">
        <thead>
        <tr>
            <th><?php echo $this->translate('Team'); ?></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php
        if (count($this->teams)>0):
        $resourceName = $resource->getControllerName();
        $team = reset($teams);
        //            $updateRight = $team->userIsAllowed('update');
        ?>
        <?php foreach ($teams as $team): ?>
            <tr>
                <td>
                    <span><?php echo $team->getName()?></span>

                    <input type="hidden" name="existing_team[]" value="<?php echo $escape($team->getId()) ?>">
                </td>
                <td>
                    <ul class="actions" style="float:right">
                        <li>
                            <?php if ($this->roleAuth()->teamAuthorized('delete', 'resource',$team->getId())): ?>
                                <a href="#" class="o-icon-delete existing" title="<?php echo $removeStr; ?>" aria-label="<?php echo $removeStr; ?>"></a>
                            <?php endif; ?>
                        </li>
                    </ul>
                </td>
            </tr>
            <tr>

            </tr>


        <?php endforeach; ?>

        </tbody>
    </table>
    <?php else:
        ?>
        <div class="no-resources">
            <p>
                <?php echo $this->translate('There are no teams for this resource.'); ?>
                <br />
                <?php echo $this->translate('Add existing teams using the interface to the right.'); ?>
            </p>
        </div>
    <?php endif; ?>
    <button id="team-selector-button" class="mobile-only"><?php echo $this->translate('Add a team'); ?></button>
    <span id="team-template" data-template="<?php echo $escape($teamTemplate); ?>"></span>

    <?php echo $this->addTeam(); //add the right sidebar control with the list of teams that can be added?>
</fieldset>
