<div>

    <select id="team_options" name="team_id" >

            <?php if ($this->current_team == null) {
    echo 'Current Team is Null';
    foreach ($this->user_teams as $team):
                    ?><option value="<?php echo $team->getTeam()->getId(); ?>"><?php echo $team->getTeam()->getName(); ?></option><?php                 endforeach; ?> <option value="null" selected>None</option><?php
} else {
                        foreach ($this->user_teams as $team):
                    ?>
                    <option <?php if ($team->getTeam()->getName() == $this->current_team) { ?>selected <?php                 } ?>value="<?php echo $team->getTeam()->getId(); ?>"><?php echo $team->getTeam()->getName(); ?></option><?php                 endforeach;
                    }?>

        </select>
</div>

<?php //$this->items = null;
