<div>
    <form id="change_team" method="post" action=" <?echo $this->url('admin/teams/current') ?>" >

        <label for="team_options"> <? echo sprintf('Showing %s for your current team: ', $this->resource_type) ?></label>
        <input type="hidden" value="<? echo $_SERVER["REQUEST_URI"]; ?>" name="return_url">
        <select id="team_options" name="team_id" form="change_team">

            <? if ($this->current_team == null){
                echo 'Current Team is Null';
                foreach ($this->user_teams as $team):
                    ?><option value="<?echo $team->getTeam()->getId();?>"><? echo $team->getTeam()->getName();?></option><?
                endforeach;
                ?> <option value="null" selected>None</option><?
            } else {

                foreach ($this->user_teams as $team):
                    ?>
                    <option <? if ($team->getTeam()->getName() == $this->current_team){ ?>selected <?
                } ?>value="<? echo $team->getTeam()->getId(); ?>"><? echo $team->getTeam()->getName(); ?></option><?
                endforeach;

            }?>

        </select>
        <button form="change_team"  formmethod="post">Change Team</button>
    </form>
</div>
