<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

echo $this->pageTitle($translate('Delete role'));
?>

<?php if ($this->role_users): ?>
    <div id="page-actions">
        <?php echo $this->hyperlink($translate('Return to Roles'), $this->url('admin/teams/roles'), ['class' => 'button']); ?>
    </div>
    <p>You can't delete this role because it is being used by the following teams</p>
    <ul class="list-group">
        <?php foreach ($role_users as $user):?>
            <li class="list-group-item"><?= $user->getTeam()->getName() ?> (<?= $user->getUser()->getName() ?>)</li>
        <?php endforeach; ?>
    </ul>

    <?php else: ?>
    <p>
        Are you sure you want to delete this role ?
    </p>
<?php
foreach ($this->role_users as $user):
    echo $user->getId();
        endforeach; ?>
<form action="<?php $this->url('admin/teams/detail/delete', ['id'=>$this->params()->fromRoute('id')])?>" method="post">
    <input class="btn btn-default" type="submit" name="confirm" value="Cancel" />
    <input class="btn btn-danger" type="submit" name="confirm" value="Delete" />
</form>
<?php endif; ?>
